tailscale/caddy-tailscale

- README.md
- module.go
This uses the protocol `tailscale+tls` to do this. This is a HACK and is intended to unblock an experiment. However this may be good enough to ship.
> Add support for listening over TLS

- Caddyfile
- app.go
- caddyfile.go
- caddyfile_test.go
- go.mod
- module.go
- module_test.go
As described in #24, this PR creates a new Caddy module registering a global configuration
option and a module fulfilling the required interface. This is an initial implementation using a
global `caddy.UsagePool` to share the configuration between the application parsed from the
caddyfile and the standalone listener functions. This will also fallback to the environment if the
configuration wasn't parsed from the Caddyfile.
In the future this can support ephemeral servers by marking the servers as ephemeral based
on the Caddy config and then stopping them in the `Stop` function.
> Support tailscale configuration via Caddy configuration

- app.go
- module.go
This lets Tailscale's logs be controlled using the normal caddy debug config directive.
Also add a deprecation warning for the `TS_AUTHKEY_{HOST}` environment variable.
/cc @clly
> use caddy's logger for tailscale logging

- module.go
- transport.go
allow specifying a node name when configuring the tailscale transport, which is used to lookup config values from the global tailscale app.
Also rename to just "Transport" and do some cleanup and simplification.
> connect reverse_proxy transport to global node config

- app.go
- module.go
Closes #22
I successfully tested this with headscale, which was pretty neat :)
> add config option for control URL

- app.go
- module.go
- module_test.go
this overrides the name used to refer to the node in the caddy config, and is mostly useful because it can include environment variables.
Closes #18
> add config option for node hostname

- README.md
In https://github.com/tailscale/caddy-tailscale/pull/35 we removed `TS_VERBOSE` env var so the Readme is now out of date.
This PR updates instructions for how to view the Tailscale login URL- I've tested that with a logger like in the example the login URL does get displayed.
Updates#cleanup
> README.md: document how to view Tailscale login URL in Caddy's logs

- README.md
- module.go
Send UserLogf messages to caddy log at INFO level. Remove instructions for enabling debug logging to get the auth URL.
> use new tsnet logging

- module.go
- transport.go
Implement reverseproxy.TLSTransport.  We go ahead and store the provided TLSConfig object, but for now we only use it to indicate that we should use TLS.  We don't actually use any of the provided values to configure the client.
Fixes #25
> transport: add TLS support

- .github/workflows/golangci-lint.yml
- .github/workflows/tests.yml
- module_test.go
Also fix some errcheck lint issues in test files.
> add GitHub Actions workflow for tests and linting

- README.md
There has been a little confusion about whether this plugin is required to use caddy with Tailscale. Add a section explaining the times the plugin might be helpful.
> readme: add "why" section

- README.md
caddy 2.8.4 fixed an issue with detecting caddyfiles, so we no longer need to explicitly specify the adapter type, since all of our config files end in `.caddyfile`.
> no need to specify caddy adapter

- auth.go
- examples/proxyauth.caddyfile
The MagicDNS suffix is what we now refer to as the "Tailnet Name": https://tailscale.com/kb/1217/tailnet-name. This code was previously using what we now call the org name, which used to be embedded in the MagicDNS name before we used ts.net cert domains.
Also add tailnet name to the output in the proxyauth example config.
Fixes #29
> set correct tailnet name in authentication provider

- command.go
- examples/proxyauth.caddyfile
Instruct caddy to use the tailscale cert manager.  Also add a --debug flag to enable debug logging with the tailscale-proxy command.
Also remove a lingering `auto_https off` config in one of our examples.
Fixes #27
> use tailscale cert manager with tailscale-proxy command

- README.md
- auth.go
- examples/auth.caddyfile
- examples/proxyauth.caddyfile
Now that we require Caddy 2.8, we can use the new RegisterDirectiveOrder func to specify the ordering of the `tailscale_auth` directive, rather than instructing users to set it manually.
> set directive order for tailscale_auth

- addresses.go
- app.go
- app_test.go
- auth.go
- command.go
- module.go
- module_test.go
- transport.go
Files copied from caddy carry the original copyright and license, though we've switched to the shorter (but equivalent) SPDX identifier. Of those, ones the we further modified for our needs also carry a Tailscale copyright.
> add missing license headers in go files 

- go.mod
- go.sum
- module.go
This provides an http.RoundTripper implementation that dynamically routes requests to the correct tsnet server's LocalAPI based on the ClientHelloInfo in the context.
Previously, we were just overriding the tscert Dialer. That worked fine the first time it dialed a LocalAPI, and would correctly dial the right tsnet server. However, tscert caches the Transport with that Dialer, so requests that should be routed to different tsnet servers would be routed incorrectly.
Updates #19
Updates #53
Updates #66
DO NOT MERGE: this relies on tailscale/tscert#11
> override tscert.TailscaledTransport with muxing transport

- auth.go
- module.go
This fixes #68 
`auth.go` was treating the listener as if it was a `tsnet.Listener`, but it was actually a `tsServerListener` which had a member (`Listener`) that implemented `tsnet.Listener`. This caused it to fall-through and try to authenticate the request through a locally-running `tailscaled`, which would fail if caddy was running in a container without one.
I'm not very familiar with go so IDK if there's a less messy-looking way to do this.
> Fix auth.go not finding the tsnet.Listener.

- README.md
- remove mention of debug logging that's no longer needed
- add note about putting state_dir on persistent volume in containers
- add note about auth provider and tagged nodes
- fix a few missing words
Updates #docs
> README.md: assorted doc updates

- README.md
Updates tailscale/tailscale#8905
> README: add docs for docker builds

- .github/workflows/golangci-lint.yml
- README.md
Also qualify caddy docker image with "docker.io/" so that the command also works with podman.
Updates #cleanup
Change-Id: Ia101a4a3005adb9118051b3416f5a64a4a45987d
> README: update caddy version in example commands

- .github/workflows/docker.yml
- Dockerfile
- README.md
This largely mirrors the default Caddy image.  (I generally use chainguard images to limit dependencies, but stuck with alpine, since that's what Caddy uses for it's main images)
The GitHub Action is duplicated from what we have for `tailscale/golink`.  I don't really know a lot of best practices for Dockerfiles, so am really looking for any input.  I have this using the `simple.caddyfile` as the default config, which is easy to override.
Updates #14
> add Dockerfile and GitHub action for building image

- app.go
- module.go
- module_test.go
Closes: https://github.com/tailscale/caddy-tailscale/issues/84
Rational:
In some environments (like docker) it is desirable to expose the tailscale port to increase direct connection success. By default ts-net when encountering a `0` port will pick a port at random. This is difficult for docker since the ports are not known. 
This work extends the node config to allow a node to gain a specific port, allowing for exposing in docker (or any other time where a user may wish to expose the port) 
Steps to test:
1. Check out branch and run `xcaddy build --with github.com/tailscale/caddy-tailscale=$(pwd)` 
2. Run the following caddyfile with `TS_AUTHKEY` in environment
```Caddyfile
{
tailscale {
ephemeral
test-caddy {
port 41650
}
other-caddy {
port 41651
}
more-other-caddy {
port 41652
}
}
} …
```
> allow port to be configured with direct assignment
